tokenlite_app/routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middle-ware group. Now create something great!
|
*/

if (application_installed()) {
    Route::get('/install/final', function () {
        return redirect('/');
    });
}

// Handle Main / Route
Route::get('/', 'Auth\LoginController@checkLoginState')->name('home');
Route::get('/locale', 'PublicController@set_lang')->name('language');

// Authenticates Routes
Route::get('/auth/{service}', 'Auth\SocialAuthController@redirect')->name('social.login');
Route::get('/auth/{service}/callback', 'Auth\SocialAuthController@callback')->name('social.login.callback');
Route::post('/auth/social/register', 'Auth\SocialAuthController@register')->name('social.register');

// Authenticates Routes
Auth::routes();
Route::get('verify/', 'Auth\VerifyController@index')->name('verify');
Route::get('verify/resend', 'Auth\VerifyController@resend')->name('verify.resend');
Route::get('verify/{id}/{token}', 'Auth\VerifyController@verify')->name('verify.email');
Route::get('verify/success', 'Auth\LoginController@verified')->name('verified');
Route::get('register/success', 'Auth\LoginController@registered')->name('registered');
Route::any('log-out', 'Auth\LoginController@logout')->name('log-out');
// Google 2FA Routes
Route::get('/login/2fa', 'Auth\SocialAuthController@show_2fa_form')->middleware('auth')->name('auth.2fa');
Route::get('/login/2fa/reset', 'Auth\SocialAuthController@show_2fa_reset_form')->name('auth.2fa.reset');
Route::post('/login/2fa/reset', 'Auth\SocialAuthController@reset_2fa');
Route::post('/login/2fa', function () {
    return redirect()->route('home');
})->middleware(['auth', 'g2fa']);

// if(is_maintenance()){
Route::get('admin/login', 'Auth\LoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Auth\LoginController@login');
Route::post('admin/logout', 'Auth\LoginController@logout')->name('admin.logout');
Route::get('admin/login/2fa', 'Auth\SocialAuthController@show_2fa_form')->middleware('auth')->name('admin.auth.2fa');
Route::post('admin/login/2fa', function () {
    return redirect()->route('home');
})->middleware(['auth', 'g2fa']);
// }

// User Routes
Route::prefix('user')->middleware(['auth', 'user', 'verify_user', 'g2fa'])->name('user.')->group(function () {
    Route::get('/', 'User\UserController@index')->name('home');
    Route::get('/account', 'User\UserController@account')->name('account');
    Route::get('/account/activity', 'User\UserController@account_activity')->name('account.activity');
    Route::get('/contribute', 'User\TokenController@index')->name('token');
    Route::get('/contribute/cancel/{gateway?}', 'User\TokenController@payment_cancel')->name('payment.cancel');
    Route::get('/transactions', 'User\TransactionController@index')->name('transactions');
    Route::get('/kyc', 'User\KycController@index')->name('kyc');
    Route::get('/kyc/application', 'User\KycController@application')->name('kyc.application');
    Route::get('/kyc/application/view', 'User\KycController@view')->name('kyc.application.view');
    Route::get('/kyc/dan', 'User\KycController@oauthDan')->name('kyc.dan');
    Route::any('/kyc/stat/dan', 'User\KycController@oauthDanStat')->name('kyc.stat');
    Route::get('/vip', 'User\UserController@vip')->name('vip');

    Route::get('/kyc-list/documents/{file}/{doc}', 'User\KycController@get_documents')
//        ->middleware('ico')
        ->name('kycs.file');

    Route::get('/password/confirm/{token}', 'User\UserController@password_confirm')->name('password.confirm');
    // Referral v1.0.3 > v1.1.1
    Route::get('/referral', 'User\UserController@referral')->name('referral');
    // My Token v1.1.2
    Route::get('/account/balance', 'User\UserController@mytoken_balance')->name('token.balance');

    // User Ajax Request
    Route::name('ajax.')->prefix('ajax')->group(function () {
        Route::post('/account/wallet-form', 'User\UserController@get_wallet_form')->name('account.wallet');
        Route::post('/account/update', 'User\UserController@account_update')
//            ->middleware('demo_user')
            ->name('account.update');
        Route::post('/contribute/access', 'User\TokenController@access')->name('token.access');
        Route::post('/contribute/payment', 'User\TokenController@payment')->name('payment');

        Route::post('/transactions/delete/{id}', 'User\TransactionController@destroy')
//            ->middleware('demo_user')
            ->name('transactions.delete');
        Route::post('/transactions/view', 'User\TransactionController@show')->name('transactions.view');
        Route::post('/kyc/submit', 'User\KycController@submit')->name('kyc.submit');
        Route::post('/account/activity', 'User\UserController@account_activity_delete')
//            ->middleware('demo_user')
            ->name('account.activity.delete');
    });
});

/*
 * Middleware removed 'ico'
 */

Route::prefix('admin')->middleware(['auth', 'admin', 'g2fa'])->name('admin.')->group(function () {
    Route::get('/', 'Admin\KycController@index')->name('kycs');
    Route::get('/dashboard', 'Admin\AdminController@index')->name('home');
    Route::any('/system-info', 'Admin\AdminController@system_info')->name('system');
    Route::any('/apps-register', 'Admin\SettingController@app_register')->name('niolite');
    Route::get('/profile', 'Admin\AdminController@profile')
//        ->middleware('ico')
        ->name('profile');
    Route::get('/profile/activity', 'Admin\AdminController@activity')
//        ->middleware('ico')
        ->name('profile.activity');
    Route::get('/password/confirm/{token}', 'Admin\AdminController@password_confirm')
        ->name('password.confirm');
    Route::get('/transactions/{state?}', 'Admin\TransactionController@index')
//        ->middleware('ico')
        ->name('transactions');
    Route::get('/check-transaction/online', 'Admin\TransactionController@checkStatus')
//        ->middleware('ico')
        ->name('transactions.check');
    Route::get('/stages/settings', 'Admin\IcoController@settings')
//        ->middleware('ico')
        ->name('stages.settings');
    Route::get('/pages', 'Admin\PageController@index')
//        ->middleware('ico')
        ->name('pages');
    Route::get('/settings', 'Admin\SettingController@index')
        ->middleware('super_admin')
//        ->middleware('ico')
        ->name('settings');
    Route::get('/settings/email', 'Admin\EmailSettingController@index')
//        ->middleware('ico')
        ->middleware('super_admin')
        ->name('settings.email');
    Route::get('/settings/referral', 'Admin\SettingController@referral_setting')
        ->middleware('super_admin')
//        ->middleware('ico')
        ->name('settings.referral'); // v1.1.2

    Route::get('/settings/rest-api', 'Admin\SettingController@api_setting')
        ->middleware('super_admin')
//        ->middleware('ico')
        ->name('settings.api'); // v1.0.6

    Route::get('/payment-methods', 'Admin\PaymentMethodController@index')
        ->middleware('super_admin')
//        ->middleware('ico')
        ->name('payments.setup');
    Route::get('/payment-methods/edit/{slug}', 'Admin\PaymentMethodController@edit')
        ->middleware('super_admin')
//        ->middleware('ico')
        ->name('payments.setup.edit');
    Route::get('/stages', 'Admin\IcoController@index')
//        ->middleware('ico')
        ->name('stages');
    Route::get('/stages/{id}', 'Admin\IcoController@edit_stage')
//        ->middleware('ico')
        ->name('stages.edit');
    Route::get('/users/{role?}', 'Admin\UsersController@index')
//        ->middleware('ico')
        ->name('users'); //v1.1.0
    Route::get('/users/wallet/change-request', 'Admin\UsersController@wallet_change_request')
//        ->middleware('ico')
        ->name('users.wallet.change');
    Route::get('/kyc-list/{status?}', 'Admin\KycController@index')
//        ->middleware('ico')
        ->name('kycs'); //v1.1.0
    Route::get('/kyc-list/documents/{file}/{doc}', 'Admin\KycController@get_documents')
//        ->middleware('ico')
        ->name('kycs.file');
    Route::get('/transactions/view/{id}', 'Admin\TransactionController@show')
        ->name('transactions.view');
    Route::get('/users/{id?}/{type?}', 'Admin\UsersController@show')
        ->name('users.view');
    Route::get('/kyc/view/{id}/{type}', 'Admin\KycController@show')
        ->name('kyc.view');
    Route::get('/pages/{slug}', 'Admin\PageController@edit')
//        ->middleware('ico')
        ->name('pages.edit');
    Route::get('/export/{table?}/{format?}', 'ExportController@export')
        ->middleware('super_admin')
//        ->middleware('ico')
//        ->middleware('demo_user')
        ->name('export'); // v1.1.0
    Route::get('/languages', 'Admin\LanguageController@index')
//        ->middleware(['ico'])
        ->name('lang.manage'); // v1.1.3
    Route::get('/languages/translate/{code}', 'Admin\LanguageController@translator')
//        ->middleware(['ico'])
        ->name('lang.translate'); // v1.1.3

    /*
     * Admin Ajax Route
     * removed line part before ->group(... :  ->middleware(['ico'])
     */

    Route::name('ajax.')->prefix('ajax')->group(function () {
        Route::post('/users/view', 'Admin\UsersController@status')
//            ->middleware('demo_user')
            ->name('users.view');
        Route::post('/users/showinfo', 'Admin\UsersController@show')->name('users.show');
        Route::post('/users/delete/all', 'Admin\UsersController@delete_unverified_user')
//            ->middleware('demo_user')
            ->name('users.delete');
        Route::post('/users/email/send', 'Admin\UsersController@send_email')

tokenlite_app/app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;
/**
 * Kyc Controller
 *
 *
 * @package TokenLite
 * @author Softnio
 * @version 1.0.6
 */

use Auth;
use Validator;
use IcoHandler;
use App\Models\KYC;
use App\Models\User;
use App\Models\UserMeta;
use App\Helpers\ReCaptcha;
use Illuminate\Http\Request;
use App\Notifications\KycStatus;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Illuminate\Http\Response;

class UserController extends Controller
{

    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\JsonResponse
     */
    public function list(Request $request, $minId, $limit)
    {
        $minId = (int) $minId;
        $limit = (int) $limit;

        $users = User::where('role', 'user')
            ->where('id', '>', $minId)
            ->take($limit)
            ->get();

        return response()->json([
            'status' => 'success',
            'data' => [
                'min_id' => $minId,
                'limit' => $limit,
                'users' => $users,
            ],
        ]);
    }


    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\JsonResponse
     */
    public function check(Request $request)
    {
        $data = $request->json()->all();

        $user = User::where('email', $data['email'])->first();

        $response = [
            'status' => 'error',
            'msg' => '',
            'data' => [],
        ];

        if (!$user) {
            $response['msg'] = 'User not found';
            return response()->json($response);
        }

        if (!Hash::check($data['password'], $user->password)) {
            $response['msg'] = 'Password wrong';
            return response()->json($response);
        }

        $response['status'] = 'success';
        $response['data'] = ['user' => $user];

        return response()->json($response);
    }

}

tokenlite_app/app/Http/Controllers/User/TransactionController.php
<?php

namespace App\Http\Controllers\User;
/**
 * Transaction Controller
 *
 *
 * @package TokenLite
 * @author Softnio
 * @version 1.0.0
 */
use Auth;
use App\Models\IcoStage;
use App\PayModule\Module;
use App\Models\Transaction;
use Illuminate\Http\Request;
use App\Notifications\TnxStatus;
use App\Http\Controllers\Controller;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     * @version 1.0.0
     * @since 1.0
     * @return void
     */
    public function index()
    {
        Transaction::where(['user' => auth()->id(), 'status' => 'new'])->delete();
        $trnxs = Transaction::where('user', Auth::id())
                    ->where('status', '!=', 'deleted')
                    ->where('status', '!=', 'new')
                    ->whereNotIn('tnx_type', ['withdraw'])
                    ->orderBy('created_at', 'DESC')->get();
        $transfers = Transaction::get_by_own(['tnx_type' => 'transfer'])->get()->count();
        $referrals = Transaction::get_by_own(['tnx_type' => 'referral'])->get()->count();
        $bonuses   = Transaction::get_by_own(['tnx_type' => 'bonus'])->get()->count();
        $refunds   = Transaction::get_by_own(['tnx_type' => 'refund'])->get()->count();
        $has_trnxs = (object) [
            'transfer' => ($transfers > 0) ? true : false,
            'referral' => ($referrals > 0) ? true : false,
            'bonus' => ($bonuses > 0) ? true : false,
            'refund' => ($refunds > 0) ? true : false
        ];
        return view('user.transactions', compact('trnxs', 'has_trnxs'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     * @version 1.0.0
     * @since 1.0
     * @return void
     *
     * @throws \Throwable
     */
    public function show(Request $request, $id='')
    {
        $module = new Module();
        $tid = ($id == '' ? $request->input('tnx_id') : $id);
        if ($tid != null) {
            $tnx = Transaction::find($tid);
            return $module->show_details($tnx);
        } else {
            return false;
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Request $request
     * @param string $id
     * @return \Illuminate\Http\Response
     * @version 1.0.0
     * @since 1.0
     */
    public function destroy(Request $request, $id='')
    {
        $tid = ($id == '' ? $request->input('tnx_id') : $id);
        if ($tid != null) {
            $tnx = Transaction::FindOrFail($tid);
            if ($tnx) {
                $old = $tnx->status;
                $tnx->status = 'deleted';
                $tnx->save();
                if ($old == 'pending' || $old == 'onhold') {
                    IcoStage::token_add_to_account($tnx, 'sub');
                }
                $ret['msg'] = 'error';
                $ret['message'] = __('messages.delete.delete', ['what'=>'Transaction']);
            } else {
                $ret['msg'] = 'warning';
                $ret['message'] = 'This transaction is not available now!';
            }
        } else {
            $ret['msg'] = 'warning';
            $ret['message'] = __('messages.delete.failed', ['what'=>'Transaction']);
        }

        if ($request->ajax()) {
            return response()->json($ret);
        }
        return back()->with([$ret['msg'] => $ret['message']]);
    }
}

tokenlite_app/resources/views/user/activity.blade.php
@extends('layouts.user')
@section('title', __('User Activity'))
@php
($has_sidebar = true)
@endphp
@section('content')
<div class="content-area card">
    <div class="card-innr">
        @include('layouts.messages')
        <div class="card-head d-flex justify-content-between">
            <h4 class="card-title card-title-md">{{__('Account Activities Log')}}</h4>
            <div class="float-right">
                <input type="hidden" id="activity_action" value="{{ route('user.ajax.account.activity.delete') }}">
                <a href="javascript:void(0)" class="btn btn-auto btn-primary btn-xs activity-delete" data-id="all">{{__('Clear All')}}</a>
            </div>
        </div>
        <div class="card-text">
            <p>{{__('Here is your recent activities. You can clear this log as well as disable the feature from profile settings tabs.')}} </p>
        </div>
        <div class="gaps-1x"></div>
        <table class="data-table dt-init activity-table" data-items="10">
            <thead>
            <tr>
                <th class="activity-time"><span>{{__('Date')}}</span></th>
                <th class="activity-device"><span>{{__('Device')}}</span></th>
                <th class="activity-browser"><span>{{__('Browser')}}</span></th>
                <th class="activity-ip"><span>{{__('IP')}}</span></th>
                <th>&nbsp;</th>
            </tr>
            </thead>
            <tbody id="activity-log">
            @forelse($activities as $activity)
                @php
                    $browser = explode('/', $activity->browser);
                    $device = explode('/', $activity->device);
                    $ip = ($activity->ip == '::1' || $activity->ip == '127.0.0.1') ? 'localhost' : $activity->ip ;
                @endphp
                <tr class="data-item activity-{{ $activity->id }}">
                    <td class="data-col">{{ _date($activity->created_at) }}</td>
                    <td class="data-col d-none d-sm-table-cell">{{ end($device) }}</td>
                    <td class="data-col">{{ $browser[0] }}</td>
                    <td class="data-col">{{ $ip }}</td>
                    <td class="data-col"><a href="javascript:void(0)" class="activity-delete fs-16" data-id="{{ $activity->id }}" title="Delete"><em class="ti-trash"></em></a></td>
                </tr>
            @empty

            @endforelse
            </tbody>
        </table>
    </div>{{-- .card-innr --}}
</div>{{-- .card --}}
@endsection

@push('header')
<script>
    var msg_delete_log = "{{ __('Once Delete, You will not get back this log in future!') }}";
</script>
@endpush

tokenlite_app/resources/views/user/dashboard.blade.php
@extends('layouts.user')
@section('title', __('User Dashboard'))
@php
    $has_sidebar = false;
    $base_currency = base_currency();
    $image = (gws('welcome_img_hide', 0)==0) ? 'welcome.png' : '';
@endphp

@section('content')
    <div class="content-area user-account-dashboard">
        @include('layouts.messages')
        <div class="row">
            <div class="col-lg-12">
                {!! UserPanel::user_balance_card($contribution, ['vers' => 'side', 'class'=> 'card-full-height']) !!}
            </div>
            <div class="col-lg-6 col-sm-12 col-mb-12">
                {!! UserPanel::user_token_block('', ['vers' => 'buy']) !!}
            </div>
            <div class="col-lg-6 col-sm-12 col-mb-12">
                <div class="account-info card card-full-height">
                    <div class="card-innr" style="display: flex;flex-direction: column;align-items: center;">
                        {!! UserPanel::user_account_status() !!}
                        <div class="gaps-2x"></div>
                        {!! UserPanel::user_account_wallet() !!}
                    </div>
                </div>
            </div>

{{--            <div class="col-12{{ (gws('user_sales_progress', 1)==1) ? ' col-lg-7' : '' }}">--}}
{{--                {!! UserPanel::content_block('welcome', ['image' => $image, 'class' => 'card-full-height']) !!}--}}
{{--            </div>--}}

{{--            <div class="col-12 col-lg-12">--}}
{{--                {!! UserPanel::token_sales_progress('',  ['class' => 'card-full-height']) !!}--}}
{{--            </div>--}}

        </div>
    </div>
@endsection

tokenlite_app/resources/views/user/kyc.blade.php
@extends('layouts.user')
@section('title', __('KYC Verification'))
@php
$has_sidebar = false;

$kyc_title = ($user_kyc !== NULL && isset($_GET['thank_you'])) ? __('Begin your ID-Verification') : __('KYC Verification');
$kyc_desc = ($user_kyc !== NULL && isset($_GET['thank_you'])) ? __('Verify your identity to participate in token sale.') : __('To comply with regulations each participant is required to go through identity verification (KYC/AML) to prevent fraud, money laundering operations, transactions banned under the sanctions regime or those which fund terrorism. Please, complete our fast and secure verification process to participate in token offerings.');
@endphp

@section('content')
<div class="page-header page-header-kyc">
    <div class="row justify-content-center">
        <div class="col-lg-8 col-xl-7 text-center">
            <h2 class="page-title">{{ $kyc_title }}</h2>
            <p class="large">{{ $kyc_desc }}</p>
        </div>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-lg-10 col-xl-9">




        <div class="content-area card user-account-pages page-kyc">
            <div class="card-innr">
                @include('layouts.messages')
                <div class="kyc-status card mx-lg-4">
                    <div class="card-innr">
                        {{-- IF NOT SUBMITED --}}
                        @if($user_kyc == NULL)
                        <div class="status status-empty">
                            <div class="status-icon">
                                <em class="ti ti-files"></em>
                            </div>
                            <span class="status-text text-dark">{{__('You have not submitted your necessary documents to verify your identity.')}}{{ (token('before_kyc')=='1') ? __('In order to purchase our tokens, please verify your identity.') : ''}}</span>
                            <p class="px-md-5">{{__('It would great if you please submit the form. If you have any question, please feel free to contact our support team.')}}</p>


                            <div class="d-flex flex-column align-items-center">
{{--                                <a href="{{ route('user.kyc.dan') }}" class="btn btn-primary m-0">{{__('Click here to complete your KYC by DAN system')}}</a>--}}
{{--                                <p class="m-2">{{ __('or') }}</p>--}}
                                <a href="{{ route('user.kyc.application') }}?state=new" class="btn btn-primary m-0">{{__("Click here to complete your KYC")}}</a>
                            </div>

                        </div>

                        @endif
                        {{-- IF SUBMITED @Thanks --}}
                        @if($user_kyc !== NULL && isset($_GET['thank_you']))
                        <div class="status status-thank px-md-5">
                            <div class="status-icon">
                                <em class="ti ti-check"></em>
                            </div>
                            <span class="status-text large text-dark">{{__('You have completed the process of KYC')}}</span>
                            <p class="px-md-5">{{__('We are still waiting for your identity verification. Once our team verified your identity, you will be notified by email. You can also check your KYC compliance status from your profile page.')}}</p>
                            <a href="{{ route('user.account') }}" class="btn btn-primary">{{__('Back to Profile')}}</a>
                        </div>
                        @endif

                        {{-- IF PENDING --}}
                        @if($user_kyc !== NULL && $user_kyc->status == 'pending' && !isset($_GET['thank_you']))
                        <div class="status status-process">
                            <div class="status-icon">
                                <em class="ti ti-infinite"></em>
                            </div>
                            <span class="status-text text-dark">{{__('Your application verification under process.')}}</span>
                            <p class="px-md-5">{{__('We are still working on your identity verification. Once our team verified your identity, you will be notified by email.')}}</p>
                        </div>
                        @endif

                        {{-- IF REJECTED/MISSING --}}
                        @if($user_kyc !== NULL && ($user_kyc->status == 'missing' || $user_kyc->status == 'rejected') && !isset($_GET['thank_you']))
                        <div class="status status{{ ($user_kyc->status == 'missing') ? '-warnning' : '-canceled' }}">
                            <div class="status-icon">
                                <em class="ti ti-na"></em>
                            </div>
                            <span class="status-text text-dark">
                                {{ $user_kyc->status == 'missing' ? __('We found some information to be missing.') : __('Sorry! Your application was rejected.') }}
                            </span>

                            <div class="alert alert-danger">
                                {{ $user_kyc->notes }}
                            </div>

                            <p class="px-md-5">{{__('In our verification process, we found information that is incorrect or missing. Please resubmit the form. In case of any issues with the submission please contact our support team.')}}</p>


                            <div class="d-flex flex-column align-items-center">
{{--                                <a href="{{ route('user.kyc.dan') }}" class="btn btn-primary m-0">{{__('Click here to complete your KYC by DAN system')}}</a>--}}
{{--                                <p class="m-2">{{ __('or') }}</p>--}}
                                <a href="{{ route('user.kyc.application') }}?state={{ $user_kyc->status == 'missing' ? 'missing' : 'resubmit' }}" class="btn btn-primary m-0">{{__('Submit Again')}}</a>
                            </div>

                        </div>
                        @endif

                        {{-- IF VERIFIED --}}
                        @if($user_kyc !== NULL && $user_kyc->status == 'approved' && !isset($_GET['thank_you']))
                        <div class="status status-verified">
                            <div class="status-icon">
                                <em class="ti ti-files"></em>
                            </div>
                            <span class="status-text text-dark">{{__('Your identity verified successfully.')}}</span>
                            <p class="px-md-5">{{__('One of our team members verified your identity. Now you can participate in our token sale. Thank you.')}}</p>
                            <div class="gaps-2x"></div>
                            <a href="{{ route('user.token') }}" class="btn btn-primary">{{__('Purchase Token')}}</a>
                        </div>
                        @endif

                    </div>
                </div>{{-- .card --}}
            </div>
        </div>

        {!! UserPanel::kyc_footer_info() !!}
    </div>
</div>
@endsection

tokenlite_app/resources/views/user/kyc_application.blade.php
@extends('layouts.user')
@section('title', __('Begin ID-Verification'))
@php
$has_sidebar = false;
@endphp

@section('content')
<div class="page-header page-header-kyc">
    <div class="row justify-content-center">
        <div class="col-lg-8 col-xl-7 text-center">
            <h2 class="page-title">{{__('Begin your ID-Verification')}}</h2>
            <p class="large">{{__('Verify your identity to participate in token sale.')}}</p>
        </div>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-lg-10 col-xl-9">

@include('layouts.messages')

<div class="kyc-form-steps card mx-lg-4">
    <input type="hidden" id="file_uploads" value="{{ route('ajax.kyc.file.upload') }}" />
    <form class="validate-modern" action="{{ route('user.ajax.kyc.submit') }}" method="POST" id="kyc_submit">
        @csrf
        @include('layouts.kyc-form')
    </form>
</div>


    </div>
</div>

@endsection

tokenlite_app/resources/views/user/kyc_dan.blade.php
@extends('layouts.user')
@section('title', __('KYC Verification'))
@php
    $has_sidebar = false;

    $kyc_title = ($user_kyc !== NULL && isset($_GET['thank_you'])) ? __('Begin your ID-Verification') : __('KYC Verification');
    $kyc_desc = ($user_kyc !== NULL && isset($_GET['thank_you'])) ? __('Verify your identity to participate in token sale.') : __('To comply with regulations each participant is required to go through identity verification (KYC/AML) to prevent fraud, money laundering operations, transactions banned under the sanctions regime or those which fund terrorism. Please, complete our fast and secure verification process to participate in token offerings.');
@endphp

@section('content')

    <h4>Redirecting ...</h4>

    <form action="{!! $formData['url'] !!}" method="GET" id="oath_dan_form">
        @foreach($formData['params'] as $key => $val)
            <div class="form-group">
                <input type="hidden" name="{!! $key !!}" value="{!! $val !!}"/>
            </div>
        @endforeach
    </form>

@endsection

@push('footer')
    <script type="text/javascript">
        $(document).ready(function () {
            $("#oath_dan_form").submit();
        });
    </script>
@endpush

tokenlite_app/resources/views/user/page.blade.php
@extends('layouts.user')
@section('title', ucfirst($page->title))
@php($has_sidebar = true)

@section('content')
<div class="content-area content-area-mh card user-account-pages page-{{ $page->slug }}">
    <div class="card-innr">
        @include('layouts.messages')
        <div class="card-head">
            <h4 class="card-title card-title-lg">{{ replace_shortcode($page->title) }}</h4>
            @if($page->meta_description!=null)
            <p class="large">{{ replace_shortcode($page->meta_description) }}</p>
            @endif
        </div>
        @if(!empty($page->description))
        <div class="card-text">
            {!! replace_shortcode(auto_p($page->description)) !!}
        </div>
        @endif
	</div>
</div>
@endsection