tokenlite_app/routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middle-ware group. Now create something great!
|
*/

if (application_installed()) {
    Route::get('/install/final', function () {
        return redirect('/');
    });
}

// Handle Main / Route
Route::get('/', 'Auth\LoginController@checkLoginState')->name('home');
Route::get('/locale', 'PublicController@set_lang')->name('language');

// Authenticates Routes
Route::get('/auth/{service}', 'Auth\SocialAuthController@redirect')->name('social.login');
Route::get('/auth/{service}/callback', 'Auth\SocialAuthController@callback')->name('social.login.callback');
Route::post('/auth/social/register', 'Auth\SocialAuthController@register')->name('social.register');

// Authenticates Routes
Auth::routes();
Route::get('verify/', 'Auth\VerifyController@index')->name('verify');
Route::get('verify/resend', 'Auth\VerifyController@resend')->name('verify.resend');
Route::get('verify/{id}/{token}', 'Auth\VerifyController@verify')->name('verify.email');
Route::get('verify/success', 'Auth\LoginController@verified')->name('verified');
Route::get('register/success', 'Auth\LoginController@registered')->name('registered');
Route::any('log-out', 'Auth\LoginController@logout')->name('log-out');
// Google 2FA Routes
Route::get('/login/2fa', 'Auth\SocialAuthController@show_2fa_form')->middleware('auth')->name('auth.2fa');
Route::get('/login/2fa/reset', 'Auth\SocialAuthController@show_2fa_reset_form')->name('auth.2fa.reset');
Route::post('/login/2fa/reset', 'Auth\SocialAuthController@reset_2fa');
Route::post('/login/2fa', function () {
    return redirect()->route('home');
})->middleware(['auth', 'g2fa']);

// if(is_maintenance()){
Route::get('admin/login', 'Auth\LoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Auth\LoginController@login');
Route::post('admin/logout', 'Auth\LoginController@logout')->name('admin.logout');
Route::get('admin/login/2fa', 'Auth\SocialAuthController@show_2fa_form')->middleware('auth')->name('admin.auth.2fa');
Route::post('admin/login/2fa', function () {
    return redirect()->route('home');
})->middleware(['auth', 'g2fa']);
// }

// User Routes
Route::prefix('user')->middleware(['auth', 'user', 'verify_user', 'g2fa'])->name('user.')->group(function () {
    Route::get('/', 'User\UserController@index')->name('home');
    Route::get('/account', 'User\UserController@account')->name('account');
    Route::get('/account/activity', 'User\UserController@account_activity')->name('account.activity');
    Route::get('/contribute', 'User\TokenController@index')->name('token');
    Route::get('/contribute/cancel/{gateway?}', 'User\TokenController@payment_cancel')->name('payment.cancel');
    Route::get('/transactions', 'User\TransactionController@index')->name('transactions');
    Route::get('/kyc', 'User\KycController@index')->name('kyc');
    Route::get('/kyc/application', 'User\KycController@application')->name('kyc.application');
    Route::get('/kyc/application/view', 'User\KycController@view')->name('kyc.application.view');
    Route::get('/kyc/dan', 'User\KycController@oauthDan')->name('kyc.dan');
    Route::any('/kyc/stat/dan', 'User\KycController@oauthDanStat')->name('kyc.stat');
    Route::get('/vip', 'User\UserController@vip')->name('vip');

    Route::get('/kyc-list/documents/{file}/{doc}', 'User\KycController@get_documents')
//        ->middleware('ico')
        ->name('kycs.file');

    Route::get('/password/confirm/{token}', 'User\UserController@password_confirm')->name('password.confirm');
    // Referral v1.0.3 > v1.1.1
    Route::get('/referral', 'User\UserController@referral')->name('referral');
    // My Token v1.1.2
    Route::get('/account/balance', 'User\UserController@mytoken_balance')->name('token.balance');

    // User Ajax Request
    Route::name('ajax.')->prefix('ajax')->group(function () {
        Route::post('/account/wallet-form', 'User\UserController@get_wallet_form')->name('account.wallet');
        Route::post('/account/update', 'User\UserController@account_update')
//            ->middleware('demo_user')
            ->name('account.update');
        Route::post('/contribute/access', 'User\TokenController@access')->name('token.access');
        Route::post('/contribute/payment', 'User\TokenController@payment')->name('payment');

        Route::post('/transactions/delete/{id}', 'User\TransactionController@destroy')
//            ->middleware('demo_user')
            ->name('transactions.delete');
        Route::post('/transactions/view', 'User\TransactionController@show')->name('transactions.view');
        Route::post('/kyc/submit', 'User\KycController@submit')->name('kyc.submit');
        Route::post('/account/activity', 'User\UserController@account_activity_delete')
//            ->middleware('demo_user')
            ->name('account.activity.delete');
    });
});

/*
 * Middleware removed 'ico'
 */

Route::prefix('admin')->middleware(['auth', 'admin', 'g2fa'])->name('admin.')->group(function () {
    Route::get('/', 'Admin\KycController@index')->name('kycs');
    Route::get('/dashboard', 'Admin\AdminController@index')->name('home');
    Route::any('/system-info', 'Admin\AdminController@system_info')->name('system');
    Route::any('/apps-register', 'Admin\SettingController@app_register')->name('niolite');
    Route::get('/profile', 'Admin\AdminController@profile')
//        ->middleware('ico')
        ->name('profile');
    Route::get('/profile/activity', 'Admin\AdminController@activity')
//        ->middleware('ico')
        ->name('profile.activity');
    Route::get('/password/confirm/{token}', 'Admin\AdminController@password_confirm')
        ->name('password.confirm');
    Route::get('/transactions/{state?}', 'Admin\TransactionController@index')
//        ->middleware('ico')
        ->name('transactions');
    Route::get('/check-transaction/online', 'Admin\TransactionController@checkStatus')
//        ->middleware('ico')
        ->name('transactions.check');
    Route::get('/stages/settings', 'Admin\IcoController@settings')
//        ->middleware('ico')
        ->name('stages.settings');
    Route::get('/pages', 'Admin\PageController@index')
//        ->middleware('ico')
        ->name('pages');
    Route::get('/settings', 'Admin\SettingController@index')
        ->middleware('super_admin')
//        ->middleware('ico')
        ->name('settings');
    Route::get('/settings/email', 'Admin\EmailSettingController@index')
//        ->middleware('ico')
        ->middleware('super_admin')
        ->name('settings.email');
    Route::get('/settings/referral', 'Admin\SettingController@referral_setting')
        ->middleware('super_admin')
//        ->middleware('ico')
        ->name('settings.referral'); // v1.1.2

    Route::get('/settings/rest-api', 'Admin\SettingController@api_setting')
        ->middleware('super_admin')
//        ->middleware('ico')
        ->name('settings.api'); // v1.0.6

    Route::get('/payment-methods', 'Admin\PaymentMethodController@index')
        ->middleware('super_admin')
//        ->middleware('ico')
        ->name('payments.setup');
    Route::get('/payment-methods/edit/{slug}', 'Admin\PaymentMethodController@edit')
        ->middleware('super_admin')
//        ->middleware('ico')
        ->name('payments.setup.edit');
    Route::get('/stages', 'Admin\IcoController@index')
//        ->middleware('ico')
        ->name('stages');
    Route::get('/stages/{id}', 'Admin\IcoController@edit_stage')
//        ->middleware('ico')
        ->name('stages.edit');
    Route::get('/users/{role?}', 'Admin\UsersController@index')
//        ->middleware('ico')
        ->name('users'); //v1.1.0
    Route::get('/users/wallet/change-request', 'Admin\UsersController@wallet_change_request')
//        ->middleware('ico')
        ->name('users.wallet.change');
    Route::get('/kyc-list/{status?}', 'Admin\KycController@index')
//        ->middleware('ico')
        ->name('kycs'); //v1.1.0
    Route::get('/kyc-list/documents/{file}/{doc}', 'Admin\KycController@get_documents')
//        ->middleware('ico')
        ->name('kycs.file');
    Route::get('/transactions/view/{id}', 'Admin\TransactionController@show')
        ->name('transactions.view');
    Route::get('/users/{id?}/{type?}', 'Admin\UsersController@show')
        ->name('users.view');
    Route::get('/kyc/view/{id}/{type}', 'Admin\KycController@show')
        ->name('kyc.view');
    Route::get('/pages/{slug}', 'Admin\PageController@edit')
//        ->middleware('ico')
        ->name('pages.edit');
    Route::get('/export/{table?}/{format?}', 'ExportController@export')
        ->middleware('super_admin')
//        ->middleware('ico')
//        ->middleware('demo_user')
        ->name('export'); // v1.1.0
    Route::get('/languages', 'Admin\LanguageController@index')
//        ->middleware(['ico'])
        ->name('lang.manage'); // v1.1.3
    Route::get('/languages/translate/{code}', 'Admin\LanguageController@translator')
//        ->middleware(['ico'])
        ->name('lang.translate'); // v1.1.3

    /*
     * Admin Ajax Route
     * removed line part before ->group(... :  ->middleware(['ico'])
     */

    Route::name('ajax.')->prefix('ajax')->group(function () {
        Route::post('/users/view', 'Admin\UsersController@status')
//            ->middleware('demo_user')
            ->name('users.view');
        Route::post('/users/showinfo', 'Admin\UsersController@show')->name('users.show');
        Route::post('/users/delete/all', 'Admin\UsersController@delete_unverified_user')
//            ->middleware('demo_user')
            ->name('users.delete');
        Route::post('/users/email/send', 'Admin\UsersController@send_email')

tokenlite_app/resources/views/admin/activity.blade.php
@extends('layouts.admin')
@section('title', 'Activity')

@section('content')
<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="main-content col-lg-12">
                @include('vendor.notice')
                <div class="card content-area content-area-mh">
                    <div class="card-innr">
                        <div class="card-head has-aside">
                            <h4 class="card-title">Recent Activity</h4>
                            <div class="card-opt">
                                <ul class="btn-grp btn-grp-block guttar-20px">
                                    <li>
                                        <input type="hidden" id="activity_action" value="{{ route('admin.ajax.profile.activity.delete') }}">
                                        <a href="javascript:void(0)" data-id="all" class="btn btn-sm btn-auto btn-primary d-sm-block d-none activity-delete"><i class="fas fa-cog mr-2"></i>Clear Log</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <table class="data-table dt-init activity-list" data-items="10">
                            <thead>
                                <tr class="data-item data-head">
                                    <th class="data-col">Date</th>
                                    <th class="data-col d-none d-sm-table-cell">Device</th>
                                    <th class="data-col">Browser</th>
                                    <th class="data-col">IP</th>
                                    <th>&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody id="activity-log">
                                @forelse($activities as $activity)
                                @php
                                $browser = explode('/', $activity->browser);
                                $device = explode('/', $activity->device);
                                $ip = ($activity->ip == '::1' || $activity->ip == '127.0.0.1') ? 'localhost' : $activity->ip ;
                                @endphp
                                <tr class="data-item activity-{{ $activity->id }}">
                                    <td class="data-col">{{ _date($activity->created_at) }}</td>
                                    <td class="data-col d-none d-sm-table-cell">{{ end($device) }}</td>
                                    <td class="data-col">{{ $browser[0] }}</td>
                                    <td class="data-col">{{ $ip }}</td>
                                    <td class="data-col"><a href="javascript:void(0)" class="activity-delete text-dark fs-12" data-id="{{ $activity->id }}" title="delete activity"><em class="fas fa-trash"></em></a></td>
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="4">No Activity Found</td>
                                </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>{{-- .card-innr --}}
                </div>{{-- .card --}}
            </div>{{-- .col --}}
        </div>{{-- .container --}}
    </div>{{-- .container --}}
</div>{{-- .page-content --}}
@endsection

tokenlite_app/resources/views/admin/language-translate-intro.blade.php
@extends('layouts.admin')
@section('title', ' Translate Language')
@push('header')
<style type="text/css">
    .sidebar-nav li.active>a {font-weight: bold;}
</style>
@endpush
@section('content')
<div class="page-content">
    <div class="container">
        @include('vendor.notice')
        <div class="row">
            <div class="col-lg-3 aside sidebar-left">
                <div class="card card-navs">
                    <div class="card-innr">
                        <div class="card-head d-none d-lg-block">
                            <h6 class="card-title card-title-md">{{ __(':lang Translation', ['lang' => $lang->name]) }}</h6>
                        </div>
                        <ul class="sidebar-nav">
                            <li><a href="{{ url()->current() }}"><em class="ikon ikon-dashboard"></em> Instruction</a></li>
                            @foreach($tags as $name => $term )
                            <li{!! (url()->full() == qs_url(['category' => $term, 'filter' => true], url()->current())) ? ' class="active"' : '' !!}><a href="{{ qs_url(['category' => $term, 'filter' => true], url()->current()) }}"><em class="ikon ikon-transactions"></em> {{ $name }}</a></li>
                            @endforeach
                            <li{!! (url()->full() == qs_url(['filter' => true], url()->current())) ? ' class="active"' : '' !!}><a href="{{ qs_url(['filter' => true], url()->current()) }}"><em class="ikon ikon-docs"></em> All Translation</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="main-content col-lg-9">
                <div class="content-area card">
                    <div class="card-innr">
                        <div class="card-head has-aside">
                            <h4 class="card-title">
                                @if( request()->filter )
                                {{ __(':page Translation', ['page' => $lang->name]) }}
                                @else
                                {{ __('Instruction for Translation') }}
                                @endif
                            </h4>
                            <div class="card-opt">
                                <ul class="btn-grp btn-grp-block guttar-20px">
                                    <li><a href="{{ route('admin.lang.manage') }}" class="btn btn-auto btn-sm btn-primary"><em class="fas fa-arrow-left"></em><span class="d-sm-inline-block d-none">Back</span></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="gaps-1-5x"></div>
                        <div class="card-text">
                            <p>You can easily translate <strong>Base</strong> text to <strong>{{ $lang->name }}</strong>. When you update please keep in mind few thing as below referrence.</p>
                            <ul class="list list-check">
                                <li>Once you change or update any text then must re-genarate the language file from Manage Languages page</li>
                                <li>Ensure that your 'resource/lang' folder have write permission.</li>
                                <li>On Leftside you have all type text, you navigate and update if you need.</li>
                                <li><p><strong>Important:</strong> If any where have '<span class="badge-lighter"> :TOKEN </span>', '<span class="badge-lighter"> :symbol </span>', '<span class="badge-lighter"> :currency </span>', '<span class="badge-lighter"> :amount </span>' or something like which is start with '<span class="badge-light"> : </span>' clone without space, please keep and use same as this is consider as variable & dynamically populate.</p></li>
                                <li><p>Example as below.<br><strong>Base:</strong> Choose currency and calculate :SYMBOL token price.</p>
                                    <p><strong>French:</strong> Choisissez la devise et calculez le prix du jeton :SYMBOL.</p>
                                    <p><strong>Turkish:</strong> Para birimini seçin ve :SYMBOL token fiyatını hesaplayın.</p>
                                </li>
                            </ul>
                            <h5 class="font-mid">DO or DONT</h5>
                            <p>
                                <em class="fa fa-check-circle text-success"></em> Use exactly what shown in Base text <span class="badge-lighter"> :SYMBOL </span> &nbsp;or <span class="badge-lighter"> :symbol </span><br>
                                <em class="fa fa-times-circle text-danger"></em> Do not use as <span class="badge-lighter"> SYMBOL: </span> &nbsp; (: colon after word) <br>
                                <em class="fa fa-times-circle text-danger"></em> Do not switch case <span class="badge-lighter"> :SYMBOL </span> &nbsp;to <span class="badge-lighter"> :symbol </span> &nbsp; or &nbsp; <span class="badge-lighter"> :symbol </span> to <span class="badge-lighter"> :SYMBOL </span>
                            </p>
                            <div class="gaps-1x"></div>
                            <p><strong>If you need any help or face problem please feel free to <a target="_blank" href="https://softnio.com/contact/">contact us</a>.</strong></p>
                        </div>
                    </div>{{-- .card-innr --}}
                </div>{{-- .card --}}
            </div>{{-- .col --}}
        </div>{{-- .row --}}
    </div>{{-- .container --}}
</div>{{-- .page-content --}}
@endsection

@push('footer')
<script type="text/javascript">
    (function($){
        var $translation = $(".lang-translation");
        if ($translation.length > 0) { ajax_form_submit($translation, false); }
    })(jQuery);
</script>
@endpush

tokenlite_app/resources/views/admin/page.blade.php
@extends('layouts.admin')
@section('title', $page->title)

@section('content')
<div class="page-content">
	<div class="container">
		<div class="row">
			<div class="main-content col-lg-12">
				<div class="content-area card">
					<div class="card-innr">
						@include('layouts.messages')
						<div class="card-head">
							<h4 class="card-title card-title-lg">{{ replace_shortcode($page->title) }}</h4>
							@if($page->meta_description!=null)
							<p class="large">{{ replace_shortcode($page->meta_description) }}</p>
							@endif
						</div>
						@if(!empty($page->description))
						<div class="card-text">
							{!! replace_shortcode(auto_p($page->description)) !!}
						</div>
						@endif
					</div>
				</div>{{-- .card --}}
			</div>{{-- .col --}}
		</div>{{-- .container --}}
	</div>{{-- .container --}}
</div>{{-- .page-content --}}
@endsection

tokenlite_app/resources/views/admin/pages.blade.php
@extends('layouts.admin')
@section('title', 'Page Manage')

@push('footer')
<link rel="stylesheet" href="{{ asset('assets/plugins/trumbowyg/ui/trumbowyg.min.css')}}?ver=1.0">
<script src="{{ asset('assets/plugins/trumbowyg/trumbowyg.min.js') }}?ver=101"></script>
@endpush

@section('content')

<div class="page-content">
    <div class="container">
        @include('vendor.notice')
        <div class="row">
            <div class="main-content col-lg-8">
                <div class="content-area card">
                    <div class="card-innr">
                        @include('layouts.messages')
                        <div class="card-head">
                            <h4 class="card-title">Pages List</h4>
                        </div>
                        <div class="gaps-1x"></div>

                        <table class="table table-even-odd table-page">
                            <thead>
                                <tr>
                                    <th>Page Title</th>
                                    <th><span>Menu Name</span></th>
                                    <th>&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($pages as $page)
                                <tr class="page-{{ $page->id }}">
                                    <td><h5>{{ str_limit($page->title, 25) }}</h5></td>
                                    <td><p>{{ $page->menu_title }}</p></td>
                                    <td class="text-right">
                                        <ul>
                                            <li><a class="btn btn-circle btn-xs btn-icon btn-lighter" href="{{ route('admin.pages.edit', ['slug'=>$page->slug]) }}" data-slug="{{ $page->slug }}" ><em class="far fa-edit"></em></a></li>
                                        </ul>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>

                    </div> {{-- .card-innr --}}

                </div> {{-- .content-area --}}
            </div>{{-- .col --}}
            <div class="aside sidebar-right col-lg-4">
                <div class="token-sales card">
                    <div class="card-innr">
                        <div class="card no-hover-shadow">
                            <div class="card-head">
                                <h5 class="card-title-md">White Paper</h5>
                            </div>
                            <div class="sap"></div>
                            <div class="pdt-3x">
                                <h6>Upload your whitepaper here.</h6>
                                <div class="upload-box">
                                    <div class="wh-upload-zone whitepaper_upload">
                                        <div class="dz-message" data-dz-message>
                                            <span class="dz-message-text">Drag and drop file</span>
                                            <span class="dz-message-or">or</span>
                                            <button type="button" class="btn btn-primary">SELECT</button>
                                        </div>
                                    </div>
                                    <input type="hidden" name="whitepaper_file" accept="application/pdf" />
                                </div>
                                <small>Accept : pdf</small>
                                <div class="hiddenFiles"></div>
                                <div class="pt-3">
                                    @if(get_setting('site_white_paper') != '')
                                    <strong>White paper : </strong><a href="{{ route('public.white.paper') }}" target="_blank" >{{get_setting('site_white_paper')}}</a>
                                    @else
                                    <p class="text-light">No file uploaded yet!</p>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>{{-- .col --}}
        </div>{{-- .row --}}
    </div>{{-- .container --}}
</div>{{-- .page-content --}}
@endsection

tokenlite_app/resources/views/admin/payments-method-edit.blade.php
@extends('layouts.admin')
@section('title', 'Edit Payment Method')

@section('content')
{{ $method }}
@endsection

tokenlite_app/resources/views/admin/payments-methods.blade.php
@extends('layouts.admin')
@section('title', 'Payment Methods')

@section('content')
<div class="page-content">
    <div class="container">
        @include('vendor.notice')
        <div class="card content-area">
            <div class="card-innr">
                <div class="card-head d-flex justify-content-between align-items-center">
                    <h4 class="card-title mb-0">Payment Methods</h4>
                    <a href="javascript:void(0)" class="btn btn-sm btn-auto btn-outline btn-primary get_pm_manage" data-type="manage_currency"><em class="fas fa-coins"></em><span class=" d-sm-inline-block d-none">Manage Currency</span></a>
                </div>
                @if(is_demo_user() || is_demo_preview()) 
                    <div class="gaps-1-5x"></div>
                    <div class="alert alert-danger">{!! __('messages.demo_payment_note') !!}</div>
                @endif 
                <div class="gaps-1x"></div>
                <div class="row guttar-vr-30px{{ (empty($methods) ? ' justify-content-center' : '') }}">
                    @forelse($methods as $method)
                    <div class="col-xl-4 col-md-6">
                        {{ $method }}
                    </div>
                    @empty
                        <div class="bg-light text-center rounded pdt-5x pdb-5x">
                            <p><em class="ti ti-package fs-24"></em><br><strong class="mt-4 fs-20 text-head">Opps!</strong><br>No available payment module package!</p>
                            <p><a class="link" href="https://softnio.com/contact/" target="_blank">Contact us our support team.</a></p>
                        </div>
                    @endforelse
                </div>
                <div class="gaps-0x"></div>
            </div>
        </div>
    </div>{{-- .container --}}
</div>{{-- .page-content --}}
@endsection

tokenlite_app/resources/views/admin/user-request.blade.php
@extends('layouts.admin')
@section('title', 'Wallet Change Request')

@push('header')
<script type="text/javascript">
    var wallet_change_url = "{{ route('admin.ajax.users.wallet.action') }}";
</script>
@endpush

@section('content')
<div class="page-content">
    <div class="container">
      <div class="content-area card">
        <div class="card-innr">
          <div class="card-head has-aside">
              <h4 class="card-title">Wallet Request List</h4>
              <div class="card-opt">
                  <ul class="btn-grp btn-grp-block guttar-20px">
                      <li>
                          <a href="{{ route('admin.users') }}" class="btn btn-auto btn-outline btn-primary btn-sm">
                              <em class="fas fa-arrow-left"> </em><span>Back <span  class="d-none d-md-inline-block">to Users</span></span>
                          </a>
                      </li>
                  </ul>
              </div>
          </div>

          <div class="gaps-1x"></div>
          <table class="data-table dt-init user-list user-request">
            <thead>
                <tr class="data-item data-head">
                    <th class="data-col request-user">User </th>
                    <th class="data-col dt-verify request-old-wallet">Old Wallet</th>
                    <th class="data-col request-new-wallet">New Wallet</th>
                    <th class="data-col"></th>
                </tr>
            </thead>
            <tbody id="request-list">
                @foreach($meta_data as $item)
                <tr class="data-item request-{{ $item->id }}">
                    <td class="data-col data-user">
                        <span class="lead user-name">{{ $item->user->name }}</span>
                        <span class="sub sub-id">{{ $item->user->email }}</span>
                    </td>
                    <td class="data-col dt-verify old-wallet">
                        <span class="lead wallet-name">{{ ucfirst($item->user->walletType) }}</span>
                        <span class="sub wallet-address">{{ show_str($item->user->walletAddress, 10) }}</span>
                    </td>
                    @php 

                    @endphp
                    <td class="data-col new-wallet">
                        <span class="lead wallet-name">{{ ucfirst($item->data()->name) }}</span>
                        <span class="sub wallet-address">{{ $item->data()->address }}</span>
                    </td>
                    <td class="data-col text-right" title="Request Date {{ _date($item->created_at) }}">
                        <div class="relative d-inline-block">
                            <a href="#" class="btn btn-light-alt btn-xs btn-icon toggle-tigger"><em class="ti ti-more-alt"></em></a>
                            <div class="toggle-class dropdown-content dropdown-content-top-left">
                                <ul class="dropdown-list">
                                   <li><a data-id="{{ $item->id }}" data-action="approve" href="javascript:void(0)" class="wallet-change-action"><em class="fa fa-check-circle"></em> Approve</a></li>
                                   <li> <a data-id="{{ $item->id }}" data-action="reject" href="javascript:void(0)" class="wallet-change-action"><em class="fa fa-times-circle"></em> Reject</a></li>
                               </ul>
                           </div>
                       </div>
                   </td>

               </tr>
               @endforeach
            </tbody>
          </table>
        </div>
      </div>{{-- .card --}}
   </div>
</div>
@endsection